version: "3.9"
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=draw_db
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - draw-db:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase
    command: tail -f /liquibase/changelog.xml
    volumes:
      - ./database/changelog.xml:/liquibase/changelog.xml
      - ./database/migrations:/liquibase/migrations

volumes:
  draw-db:
  pgadmin:
    driver: local

networks:
  ting: