// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: draw.sql

package repository

import (
	"context"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO draws (
  host_id,
  guest_id
) VALUES (
  $1, $2
)
RETURNING id, host_id, guest_id
`

type CreateMatchParams struct {
	HostID  int32
	GuestID int32
}

func (q *Queries) CreateMatch(ctx context.Context, db DBTX, arg CreateMatchParams) (Draw, error) {
	row := db.QueryRow(ctx, createMatch, arg.HostID, arg.GuestID)
	var i Draw
	err := row.Scan(&i.ID, &i.HostID, &i.GuestID)
	return i, err
}
