// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Club struct {
	ID          int64
	Name        string
	Nationality string
	Seed        int32
	CreatedAt   pgtype.Timestamptz
}

type Draw struct {
	ID      int64
	HostID  int32
	GuestID int32
}
